# Generated by Django 6.0.3 on 2026-03-23 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên trạm')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('total_slots', models.IntegerField(default=0, verbose_name='Tổng số chỗ')),
                ('available_slots', models.IntegerField(default=0, verbose_name='Số chỗ còn trống')),
            ],
        ),
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='ID người dùng')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Giờ bắt đầu')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Giờ kết thúc')),
                ('status', models.CharField(default='In Progress', max_length=50)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='charging_api.chargingstation')),
            ],
        ),
    ]
