# Generated by Django 6.0.3 on 2026-03-23 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_api', '0002_chargingstation_latitude_chargingstation_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='available_slots',
            field=models.IntegerField(default=0, verbose_name='Chỗ trống hiện tại'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kinh độ'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='ID Người dùng')),
                ('booking_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm đặt')),
                ('expiry_time', models.DateTimeField(verbose_name='Thời hạn giữ chỗ')),
                ('status', models.CharField(choices=[('Pending', 'Chờ thanh toán'), ('Confirmed', 'Đã giữ chỗ'), ('Completed', 'Đã sạc xong'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20)),
                ('qr_code_data', models.TextField(blank=True, null=True, verbose_name='Dữ liệu QR')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Số tiền cọc')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='charging_api.chargingstation')),
            ],
        ),
        migrations.DeleteModel(
            name='ChargingSession',
        ),
    ]
