# Generated by Django 6.0.3 on 2026-03-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_api', '0003_alter_chargingstation_available_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời hạn giữ chỗ'),
        ),
    ]
