# Generated by Django 6.0.3 on 2026-03-23 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_api', '0004_alter_booking_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='qr_code_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charging_api.chargingstation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.CharField(max_length=100, verbose_name='ID người dùng'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='available_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='total_slots',
            field=models.IntegerField(default=0),
        ),
    ]
