# Generated by Django 6.0.3 on 2026-03-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_api', '0006_alter_chargingstation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
