# Generated by Django 6.0.3 on 2026-04-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_api', '0007_alter_chargingstation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='ward',
            field=models.CharField(default='Khác', max_length=100, verbose_name='Phường/Xã'),
        ),
    ]
