# Generated by Django 6.0.3 on 2026-04-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_api', '0008_chargingstation_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Quick_Booking', 'Đang giữ chỗ 10p'), ('Confirmed', 'Đã giữ chỗ/Đang sạc'), ('Completed', 'Đã sạc xong'), ('Cancelled', 'Đã hủy/Hết hạn')], default='Quick_Booking', max_length=20),
        ),
    ]
