# Generated by Django 6.0.4 on 2026-04-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_api', '0009_booking_is_checked_in_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
    ]
