# Generated by Django 6.0.4 on 2026-04-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_api', '0013_chargingslot_booking_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
