# Generated by Django 6.0.4 on 2026-05-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_api', '0015_alter_chargingstation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='scheduled_hour',
            field=models.IntegerField(blank=True, null=True, verbose_name='Khung giờ đặt (0-23)'),
        ),
    ]
