# Generated by Django 6.0.4 on 2026-05-04 15:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_api', '0016_booking_scheduled_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_available', models.BooleanField(default=True)),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='charging_api.chargingslot')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='charging_api.chargingstation')),
            ],
            options={
                'unique_together': {('station', 'slot', 'date', 'start_hour')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charging_api.timeslot'),
        ),
    ]
