# Generated by Django 6.0.4 on 2026-05-06 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging_api', '0017_timeslot_booking_time_slot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('station', 'slot', 'start_hour')},
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='date',
        ),
    ]
